### ISSUE TITLE
monitor the refresh status doesn't work

### ISSUE THREAD

**Issue by JichinX** [android/codelab-android-paging#140]
SearchRepositoriesActivity -> initAdapter:
```
//...
 adapter.addLoadStateListener { loadState ->
        // Only show the list if refresh succeeds.
        binding.list.isVisible = loadState.source.refresh is LoadState.NotLoading
        // Show loading spinner during initial load or refresh.
        binding.progressBar.isVisible = loadState.source.refresh is LoadState.Loading
        // Show the retry state if initial load or refresh fails.
        binding.retryButton.isVisible = loadState.source.refresh is LoadState.Error
//...
```
It is effective before using `RemoteMediator`.
after using `RemoteMediator`,` loadState.source.refresh` is always `NotLoading` because `Error` or `Loading` is now changed within `loadState.mediator`
so, I replace `loadState.source.refresh` with `loadState.refresh` and it works look good .

This is my personal opinion,Thanks

**Comment by xujichang** [comment]
before:
<img src="https://user-images.githubusercontent.com/13867911/103052226-90854080-45d3-11eb-9bbb-327d4268027f.png" width = "30%"   />
after changed:
<img src="https://user-images.githubusercontent.com/13867911/103052298-c0ccdf00-45d3-11eb-95ee-44d8c223c969.png" width = "30%" />
<img src="https://user-images.githubusercontent.com/13867911/103052349-e22dcb00-45d3-11eb-9e75-294d53aa7ecb.png" width = "30%"  />

**Comment by florina-muntenescu** [comment]
If you only show the list when `loadState.refresh is LoadState.NotLoading` then you have items in your database that are not actually displayed. 
For good user experience, you should be able to show items even if the device is offline.
